### ISSUE TITLE
Unable to Install on Grafana 2.5

### ISSUE THREAD

**Issue by danielladd** [grafana/panel-plugin-piechart#12]
I am attempting to install the piechart plugin on my Grafana v2.5 environment and no matter what I do the panel does now show as an option in the UI. I cloned the repository to /var/lib/grafana/plugins as documented and restarted the grafana-server service and that did not work. I also tried putting the plugin in a separate directory and referencing it as:

[plugin.piechart]
path = /home/usr/share/grafana/panel-plugin-piechart

I made sure that the grafana service has ownership of the plugin directory, and checked the grafana logs but it did not have useful information.

My installation was handled by this chef cookbook:
https://supermarket.chef.io/cookbooks/grafana

**Comment by nopzor1200** [comment]
Hi danielladd,

Give it a shot with the latest code (ie. master branch, or nightly builds) to utilize the plugin functionality. Plugin functionality is still in active development.

**Comment by danielladd** [comment]
Hi nopzor1200, 
Thanks for the quick response, I will give that a try!
