### ISSUE TITLE
Plugin not detected

### ISSUE THREAD

**Issue by floppy84** [grafana/panel-plugin-piechart#4]
Hi all,

I try to install pie chart plugin but it's not detected.

i have installed it to /var/lib/grafana/plugins

and restarted grafana but no plugin appeared.

So i specified in grafana.ini

[plugin.piechart]
path =  /var/lib/grafana/plugins/panel-plugin-piechart

bu no success and no error in grafana log.

my grafana is 2.6 version installed via rpm.

Is there something that i missed.

thanks

**Comment by bergquist** [comment]
Do you see Plugin "Scaning dir /var/lib/grafana/plugins/panel-plugin-piechart" in the logs?
otherwise it's an configuration error.

**Comment by floppy84** [comment]
No i don't see that. Do i need to activation feature plugin somewhere ?

**Comment by woodsaj** [comment]
@floppy84 grafana2.6 does not support support panelPlugins. PanelPlugins are a feature of grafana3.0.0. You can get pre-release versions from the nightly builds available at http://grafana.org/download/builds.html.   The nightly builds are generally pretty stable, but you should still use caution with them.

**Comment by floppy84** [comment]
@woodsaj oh !!! thanks i was pretty sure that i missed something.
Okay good to know.

I don't want to deploy on production a version not yet released.
But because i am so curious i will try on staging vm.

Many thanks for your answer.
