### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by grawcho** [grafana/panel-plugin-piechart#6]
Having trouble getting the plugin to work (probably missing something basic), i followed the README file on Ubuntu machine, server installed from apt list (2.5 stable). will appreciate any pointers or revised README :) :+1:

**Comment by woodsaj** [comment]
panel plugins only work with what will be Grafana3.0.  This is still in development but you can download nightly pre-release builds from http://grafana.org/download/builds

**Comment by grawcho** [comment]
thanks, i'll try installing the pre-release version.

**Comment by grawcho** [comment]
done, with 3.0 pre-release (Closing the issue)
