### ISSUE TITLE
How do I install ?

### ISSUE THREAD

**Issue by h4wkmoon** [grafana/panel-plugin-piechart#8]
Hi, 
I read the readme like a good boy, and followed its instructions.
l can't make the pie panel appear.

I've cloned the git repo in the plugins dir, which did not exist first. Not working.
I've added the section in the grafana.ini, which is not supposed to be necessary. Not working. I receive an error in the log. Maybe this plugins does not work with Grafana 2.6.
Am I missing something ?

`
Unknown config section plugin.piechart defined in /etc/grafana/grafana.ini
`

**Comment by xadhoom** [comment]
you need grafana master to have support for plugins.
on grafana website there're also packages of latest git master, if you don't want to build it (like me, lol)

**Comment by h4wkmoon** [comment]
Thanks, the install works! 
I will make a pull request for the readme.md to update it.
